package model;

import oracle.jbo.Row;
import oracle.jbo.ViewCriteria;
import oracle.jbo.ViewCriteriaRow;
import oracle.jbo.ViewObject;
import oracle.jbo.server.ApplicationModuleImpl;
import oracle.jbo.server.ViewLinkImpl;
import oracle.jbo.server.ViewObjectImpl;

// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Sun Apr 05 12:01:22 CEST 2015
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class AppModuleImpl extends ApplicationModuleImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public AppModuleImpl() {
    }

    public void getdemande(){
        
        
        }

    /**
     * Container's getter for DemandeDeCongeView1.
     * @return DemandeDeCongeView1
     */
    public DemandeDeCongeViewImpl getDemandeDeCongeView1() {
        return (DemandeDeCongeViewImpl)findViewObject("DemandeDeCongeView1");
    }

    /**
     * Container's getter for EmployeView1.
     * @return EmployeView1
     */
    public ViewObjectImpl getEmployeView1() {
        return (ViewObjectImpl)findViewObject("EmployeView1");
    }

    /**
     * Container's getter for EtatCongeView1.
     * @return EtatCongeView1
     */
    public ViewObjectImpl getEtatCongeView1() {
        return (ViewObjectImpl)findViewObject("EtatCongeView1");
    }

    /**
     * Container's getter for HistoriqueCongeView1.
     * @return HistoriqueCongeView1
     */
    public ViewObjectImpl getHistoriqueCongeView1() {
        return (ViewObjectImpl)findViewObject("HistoriqueCongeView1");
    }

    /**
     * Container's getter for ProfilView1.
     * @return ProfilView1
     */
    public ViewObjectImpl getProfilView1() {
        return (ViewObjectImpl)findViewObject("ProfilView1");
    }

    /**
     * Container's getter for SoldeEmployeView1.
     * @return SoldeEmployeView1
     */
    public ViewObjectImpl getSoldeEmployeView1() {
        return (ViewObjectImpl)findViewObject("SoldeEmployeView1");
    }

    /**
     * Container's getter for TypeCongeView1.
     * @return TypeCongeView1
     */
    public ViewObjectImpl getTypeCongeView1() {
        return (ViewObjectImpl)findViewObject("TypeCongeView1");
    }

    /**
     * Container's getter for SoldeEmployeView1_1.
     * @return SoldeEmployeView1_1
     */
    public ViewObjectImpl getSoldeEmployeView1_1() {
        return (ViewObjectImpl)findViewObject("SoldeEmployeView1_1");
    }

    /**
     * Container's getter for TypeCongeView1_1.
     * @return TypeCongeView1_1
     */
    public ViewObjectImpl getTypeCongeView1_1() {
        return (ViewObjectImpl)findViewObject("TypeCongeView1_1");
    }

    /**
     * Container's getter for ProfilView1_1.
     * @return ProfilView1_1
     */
    public ViewObjectImpl getProfilView1_1() {
        return (ViewObjectImpl)findViewObject("ProfilView1_1");
    }

    /**
     * Container's getter for HistoriqueCongeView1_1.
     * @return HistoriqueCongeView1_1
     */
    public ViewObjectImpl getHistoriqueCongeView1_1() {
        return (ViewObjectImpl)findViewObject("HistoriqueCongeView1_1");
    }

    /**
     * Container's getter for EtatCongeView1_1.
     * @return EtatCongeView1_1
     */
    public ViewObjectImpl getEtatCongeView1_1() {
        return (ViewObjectImpl)findViewObject("EtatCongeView1_1");
    }

    /**
     * Container's getter for EmployeView1_1.
     * @return EmployeView1_1
     */
    public ViewObjectImpl getEmployeView1_1() {
        return (ViewObjectImpl)findViewObject("EmployeView1_1");
    }

    /**
     * Container's getter for DemandeDeCongeView1_1.
     * @return DemandeDeCongeView1_1
     */
    public ViewObjectImpl getDemandeDeCongeView1_1() {
        return (ViewObjectImpl)findViewObject("DemandeDeCongeView1_1");
    }

    /**
     * Container's getter for SoldeEmployeView2.
     * @return SoldeEmployeView2
     */
    public ViewObjectImpl getSoldeEmployeView2() {
        return (ViewObjectImpl)findViewObject("SoldeEmployeView2");
    }

    /**
     * Container's getter for SoldeEmployeView3.
     * @return SoldeEmployeView3
     */
    public ViewObjectImpl getSoldeEmployeView3() {
        return (ViewObjectImpl)findViewObject("SoldeEmployeView3");
    }

    /**
     * Container's getter for ProfilView2.
     * @return ProfilView2
     */
    public ViewObjectImpl getProfilView2() {
        return (ViewObjectImpl)findViewObject("ProfilView2");
    }

    /**
     * Container's getter for DemandeDeCongeView2.
     * @return DemandeDeCongeView2
     */
    public DemandeDeCongeViewImpl getDemandeDeCongeView2() {
        return (DemandeDeCongeViewImpl)findViewObject("DemandeDeCongeView2");
    }

    /**
     * Container's getter for DemandeDeCongeView3.
     * @return DemandeDeCongeView3
     */
    public DemandeDeCongeViewImpl getDemandeDeCongeView3() {
        return (DemandeDeCongeViewImpl)findViewObject("DemandeDeCongeView3");
    }

    /**
     * Container's getter for DemandeDeCongeView4.
     * @return DemandeDeCongeView4
     */
    public DemandeDeCongeViewImpl getDemandeDeCongeView4() {
        return (DemandeDeCongeViewImpl)findViewObject("DemandeDeCongeView4");
    }

    /**
     * Container's getter for SoldeEmployeView1_2.
     * @return SoldeEmployeView1_2
     */
    public ViewObjectImpl getSoldeEmployeView1_2() {
        return (ViewObjectImpl)findViewObject("SoldeEmployeView1_2");
    }

    /**
     * Container's getter for DemandeDeCongeView1_2.
     * @return DemandeDeCongeView1_2
     */
    public ViewObjectImpl getDemandeDeCongeView1_2() {
        return (ViewObjectImpl)findViewObject("DemandeDeCongeView1_2");
    }

    /**
     * Container's getter for DemandeDeCongeView1_3.
     * @return DemandeDeCongeView1_3
     */
    public ViewObjectImpl getDemandeDeCongeView1_3() {
        return (ViewObjectImpl)findViewObject("DemandeDeCongeView1_3");
    }

    /**
     * Container's getter for SoldeEmployeView1_3.
     * @return SoldeEmployeView1_3
     */
    public ViewObjectImpl getSoldeEmployeView1_3() {
        return (ViewObjectImpl)findViewObject("SoldeEmployeView1_3");
    }

    /**
     * Container's getter for ProfilView1_2.
     * @return ProfilView1_2
     */
    public ViewObjectImpl getProfilView1_2() {
        return (ViewObjectImpl)findViewObject("ProfilView1_2");
    }
    
    
    
    
    
    
    
    
    
    
    public  UserInfo testUser(String userName,String password){
           
               UserInfo user = null;
               
               ViewObject vo = getProfilView1();
               ViewCriteria vc = vo.createViewCriteria();
                
               ViewCriteriaRow vcr = vc.createViewCriteriaRow();
               vcr.setAttribute("Login",userName);
               vcr.setAttribute("Pwd",password);
               
               vc.add(vcr);
                 
               vo.applyViewCriteria(vc);
               
               
               vo.executeQuery();
               
           if(vo.hasNext()){
                         System.out.println("haaaas nexxxxt");
                         user= new UserInfo();
                         Row row = vo.next();


                         String name = (String)row.getAttribute("Login");
                         user.setLogin(name);
                         
                         String pass = (String)row.getAttribute("Pwd");
                         user.setPwd(pass);
                         
                         
                        
                         
                       }
                       return user;
               }
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    

    /**
     * Container's getter for DemandeDeCongeView1_4.
     * @return DemandeDeCongeView1_4
     */
    public ViewObjectImpl getDemandeDeCongeView1_4() {
        return (ViewObjectImpl)findViewObject("DemandeDeCongeView1_4");
    }

    /**
     * Container's getter for SoldeEmployeConLink1.
     * @return SoldeEmployeConLink1
     */
    public ViewLinkImpl getSoldeEmployeConLink1() {
        return (ViewLinkImpl)findViewLink("SoldeEmployeConLink1");
    }

    /**
     * Container's getter for SoldeEmployeConnLink1.
     * @return SoldeEmployeConnLink1
     */
    public ViewLinkImpl getSoldeEmployeConnLink1() {
        return (ViewLinkImpl)findViewLink("SoldeEmployeConnLink1");
    }

    /**
     * Container's getter for ProfilConnLink1.
     * @return ProfilConnLink1
     */
    public ViewLinkImpl getProfilConnLink1() {
        return (ViewLinkImpl)findViewLink("ProfilConnLink1");
    }

    /**
     * Container's getter for DemandeDLink1.
     * @return DemandeDLink1
     */
    public ViewLinkImpl getDemandeDLink1() {
        return (ViewLinkImpl)findViewLink("DemandeDLink1");
    }

    /**
     * Container's getter for DemandeDeconLink1.
     * @return DemandeDeconLink1
     */
    public ViewLinkImpl getDemandeDeconLink1() {
        return (ViewLinkImpl)findViewLink("DemandeDeconLink1");
    }

    /**
     * Container's getter for DemandeDeCongeConLink1.
     * @return DemandeDeCongeConLink1
     */
    public ViewLinkImpl getDemandeDeCongeConLink1() {
        return (ViewLinkImpl)findViewLink("DemandeDeCongeConLink1");
    }

    /**
     * Container's getter for SoldeEmployeConLink1_1.
     * @return SoldeEmployeConLink1_1
     */
    public ViewLinkImpl getSoldeEmployeConLink1_1() {
        return (ViewLinkImpl)findViewLink("SoldeEmployeConLink1_1");
    }

    /**
     * Container's getter for DemandeDeconLink1_1.
     * @return DemandeDeconLink1_1
     */
    public ViewLinkImpl getDemandeDeconLink1_1() {
        return (ViewLinkImpl)findViewLink("DemandeDeconLink1_1");
    }

    /**
     * Container's getter for DemandeDLink1_1.
     * @return DemandeDLink1_1
     */
    public ViewLinkImpl getDemandeDLink1_1() {
        return (ViewLinkImpl)findViewLink("DemandeDLink1_1");
    }

    /**
     * Container's getter for SoldeEmployeConnLink1_1.
     * @return SoldeEmployeConnLink1_1
     */
    public ViewLinkImpl getSoldeEmployeConnLink1_1() {
        return (ViewLinkImpl)findViewLink("SoldeEmployeConnLink1_1");
    }

    /**
     * Container's getter for ProfilConnLink1_1.
     * @return ProfilConnLink1_1
     */
    public ViewLinkImpl getProfilConnLink1_1() {
        return (ViewLinkImpl)findViewLink("ProfilConnLink1_1");
    }

    /**
     * Container's getter for DemandeDeCongeConLink1_1.
     * @return DemandeDeCongeConLink1_1
     */
    public ViewLinkImpl getDemandeDeCongeConLink1_1() {
        return (ViewLinkImpl)findViewLink("DemandeDeCongeConLink1_1");
    }

    /**
     * Container's getter for DemandeDeCongeView1Ex1.
     * @return DemandeDeCongeView1Ex1
     */
    public ViewObjectImpl getDemandeDeCongeView1Ex1() {
        return (ViewObjectImpl)findViewObject("DemandeDeCongeView1Ex1");
    }

    /**
     * Container's getter for DemandeDeCongeViewEx111_1.
     * @return DemandeDeCongeViewEx111_1
     */
    public DemandeDeCongeViewImpl getDemandeDeCongeViewEx111_1() {
        return (DemandeDeCongeViewImpl)findViewObject("DemandeDeCongeViewEx111_1");
    }

    /**
     * Container's getter for DemandeDeCongeExView1.
     * @return DemandeDeCongeExView1
     */
    public ViewObjectImpl getDemandeDeCongeExView1() {
        return (ViewObjectImpl)findViewObject("DemandeDeCongeExView1");
    }

    /**
     * Container's getter for DemandedrhviewView1.
     * @return DemandedrhviewView1
     */
    public ViewObjectImpl getDemandedrhviewView1() {
        return (ViewObjectImpl)findViewObject("DemandedrhviewView1");
    }

    /**
     * Container's getter for DemandeDeConge1View1.
     * @return DemandeDeConge1View1
     */
    public ViewObjectImpl getDemandeDeConge1View1() {
        return (ViewObjectImpl)findViewObject("DemandeDeConge1View1");
    }

    /**
     * Container's getter for DemandeDeConge1View1_1.
     * @return DemandeDeConge1View1_1
     */
    public ViewObjectImpl getDemandeDeConge1View1_1() {
        return (ViewObjectImpl)findViewObject("DemandeDeConge1View1_1");
    }

    /**
     * Container's getter for Employe1View1.
     * @return Employe1View1
     */
    public ViewObjectImpl getEmploye1View1() {
        return (ViewObjectImpl)findViewObject("Employe1View1");
    }

    /**
     * Container's getter for Employe1View1_1.
     * @return Employe1View1_1
     */
    public ViewObjectImpl getEmploye1View1_1() {
        return (ViewObjectImpl)findViewObject("Employe1View1_1");
    }

    /**
     * Container's getter for HistoriqueConge1View1.
     * @return HistoriqueConge1View1
     */
    public ViewObjectImpl getHistoriqueConge1View1() {
        return (ViewObjectImpl)findViewObject("HistoriqueConge1View1");
    }

    /**
     * Container's getter for HistoriqueConge1View1_1.
     * @return HistoriqueConge1View1_1
     */
    public ViewObjectImpl getHistoriqueConge1View1_1() {
        return (ViewObjectImpl)findViewObject("HistoriqueConge1View1_1");
    }
}
